import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://fiestacabs.com";

  // Define your static routes here
  const staticRoutes = [
    "",
    "/about-us",
    "/airport-transportation-services",
    "/best-car-rental-in-chennai",
    "/blog",
    "/blog/best-car-rental-in-chennai-with-driver-affordable-reliable-service",
    "/blog/daily-office-pickup-and-drop-service-in-bangalore",
    "/blog/enhancing-the-mobility-of-people-strategies-for-effective-integration",
    "/blog/essential-guide-to-wedding-car-rental-for-your-special-day",
    "/blog/ets",
    "/blog/office-pickup-and-drop-service-in-chennai",
    "/blog/office-pickup-and-drop-service-in-delhi",
    "/blog/office-pickup-and-drop-service-in-gurgaon",
    "/blog/office-pickup-and-drop-service-in-hyderabad",
    "/blog/office-pickup-and-drop-service-in-kolkata",
    "/blog/office-pickup-and-drop-service-in-mumbai",
    "/blog/office-pickup-and-drop-service-in-pune",
    "/blog/top-corporate-employee-transportation-for-enhanced-efficiency",
    "/blog/top-shuttle-service-solutions-for-your-daily-commute-needs",
    "/blog/understanding-nodal-point-transport-key-insights-and-applications",
    "/car-rent-for-marriage-in-delhi",
    "/careers",
    "/clients",
    "/corporate-car-rental-in-bangalore",
    "/corporate-car-rental-in-delhi",
    "/corporate-car-rental-in-hyderabad",
    "/corporate-car-rental-in-mumbai",
    "/corporate-car-rental-in-pune",
    "/corporate-car-rental-service",
    "/employee-transport-services",
    "/employee-transportation-services-in-bangalore",
    "/employee-transportation-services-in-chennai",
    "/employee-transportation-services-in-delhi",
    "/employee-transportation-services-in-gurgaon",
    "/employee-transportation-services-in-hyderabad",
    "/employee-transportation-services-in-kolkata",
    "/employee-transportation-services-in-mumbai",
    "/employee-transportation-services-in-pune",
    "/gallery",
    "/our-journey",
    "/outstation-cabs-in-bangalore",
    "/outstation-cabs-in-chennai",
    "/outstation-cabs-in-delhi",
    "/outstation-cabs-in-hyderabad",
    "/outstation-cabs-in-mumbai",
    "/outstation-cabs-in-pune",
    "/outstation-rides",
    "/premium-car-rentals",
    "/privacy-policy",
    "/reach-us",
    "/services-offered",
    "/shutle-services-in-pune",
    "/shuttle-service",
    "/shuttle-service-in-bangalore",
    "/shuttle-service-in-delhi",
    "/shuttle-service-in-gurgaon",
    "/shuttle-services-in-chennai",
    "/shuttle-services-in-hyderabad",
    "/shuttle-services-in-mumbai",
    "/terms-and-conditions",
    "/wedding-car-rental-in-chennai",
    "/wedding-car-rental-mumbai",
    "/wedding-cars",
    "/wedding-cars-in-bangalore",
    "/wedding-cars-in-hyderabad",
  ];

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: route === "" ? 1 : 0.8,
  }));
}
